apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: imy6ey5or-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: imy6ey5or-nodejs 
  name: imy6ey5or-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: imy6ey5or-nodejs 
