apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: imy6ey5or-nodejs 
  janus-idp.io/tekton: imy6ey5or-nodejs
  backstage.io/kubernetes-id: imy6ey5or-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: imy6ey5or-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml